Platforms/ARM/Juno: Add GCC ARMv8 target architecture flag
This commit adds the GCC compiler "-march=armv8-a" flag
for the Juno platform with ARMv8 CPU.

This compilation flag also fixes assembler errors like
 Error: attempt to use an ARM instruction on a Thumb-only processor
 -- `push {r4-r8}'
which are reported by GCC compilers prior to
Linaro GCC 4.9-2015.05 4.9.3 20150413 (i.e. 4.9.3 20141119).

Change-Id: I189ddaaa031681ff6e378de78ab1e1560f36ab18
Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: Alexei Fedorov <alexei.fedorov@arm.com>
Signed-off-by: Evan Lloyd <evan.lloyd@arm.com>