Platforms/ARM/Juno/AcpiTables: Fix FADT Compilation Bug
 #if ARM_JUNO_ACPI_5_0
causes the GCC error listed below
k:\edk2\OpenPlatformPkg\Platforms\ARM\Juno\AcpiTables\Fadt.aslc:76:22:
 error: #if with no expression
when ARM_JUNO_ACPI_5_0 is defined in
 edk2\ArmPlatformPkg\ArmJunoPkg\Include\ArmPlatform.h:
The problem occurs because the macro is defined but has no value.

The bug is corrected by replacing
 #if ARM_JUNO_ACPI_5_0
with
 #ifdef ARM_JUNO_ACPI_5_0
This usage is also consistent with that on line 20

Change-Id: I5f3903ca96bd11ef383bac5ddcff1923090641e2
Contributed-under: TianoCore Contribution Agreement 1.0
Signed-off-by: Alexei Fedorov <Alexei.Fedorov@arm.com>
Signed-off-by: Evan Lloyd <Evan.Lloyd@arm.com>